### ISSUE TITLE
pybids stumbles over `CHANGES` file

### ISSUE THREAD

**Issue by mih** [datalad/datalad-neuroimaging#18]
With #17 I see this locally:

```
======================================================================
ERROR: datalad_neuroimaging.tests.test_dicomconv.test_validate_bids_fixture
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/tests/test_dicomconv.py", line 39, in test_validate_bids_fixture
    bids_ds = get_bids_dataset()
  File "/home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/tests/utils.py", line 94, in get_bids_dataset
    bids_ds.aggregate_metadata(recursive=False, incremental=True)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/wrapt/wrappers.py", line 562, in __call__
    args, kwargs)
  File "/home/mih/hacking/datalad/git/datalad/distribution/dataset.py", line 439, in apply_func
    return f(**kwargs)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 470, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/mih/env/datalad3-dev/lib/python3.6/site-packages/wrapt/wrappers.py", line 523, in __call__
    args, kwargs)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 458, in return_func
    results = list(results)
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 414, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/mih/hacking/datalad/git/datalad/interface/utils.py", line 482, in _process_results
    for res in results:
  File "/home/mih/hacking/datalad/git/datalad/metadata/aggregate.py", line 721, in __call__
    to_save)
  File "/home/mih/hacking/datalad/git/datalad/metadata/aggregate.py", line 206, in _extract_metadata
    paths=relevant_paths)
  File "/home/mih/hacking/datalad/git/datalad/metadata/metadata.py", line 517, in _get_metadata
    for loc, meta in contentmeta_t or {}:
  File "/home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/extractors/bids.py", line 168, in _get_cnmeta
    include_entities=True).items()
  File "/home/mih/hacking/pybids/bids/grabbids/bids_layout.py", line 184, in get_metadata
    potentialJSONs = self._get_nearest_helper(path, '.json', **kwargs)
  File "/home/mih/hacking/pybids/bids/grabbids/bids_layout.py", line 152, in _get_nearest_helper
    "likely because it is not a valid BIDS file." % path
ValueError: File '/home/mih/hacking/datalad/datalad-neuroimaging/datalad_neuroimaging/tests/data/bids/CHANGES' does not have a valid type definition, most likely because it is not a valid BIDS file.
```

but strangely only within nose, but not when called like this:

```
python -c 'from datalad_neuroimaging.tests.utils import get_bids_dataset; get_bids_dataset()'
```

**Comment by mih** [comment]
Ran it with DATALAD_RUNTIME_RAISEONERROR=1
