### ISSUE TITLE
test_bids2scidata AssertionError

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-neuroimaging#82]
daily run
https://github.com/datalad/datalad-extensions/runs/603788377

```
. (dataset): datalad_core,datalad_unique_content_properties,dicom
======================================================================
. (dataset): datalad_core,datalad_unique_content_properties,dicom
FAIL: datalad_neuroimaging.tests.test_bids2scidata.test_real_ds
. (dataset): datalad_core,datalad_unique_content_properties,nidm
----------------------------------------------------------------------
nifti1.nii.gz (file): annex,nifti1
Traceback (most recent call last):
. (dataset): bids,datalad_core,datalad_unique_content_properties
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
. (dataset): bids,datalad_core,datalad_unique_content_properties
    self.test(*self.arg)
. (dataset): aggregated
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 691, in newfunc
acq100 (dataset): aggregated
    return t(*(arg + (filename,)), **kw)
. (dataset): bids,datalad_core,datalad_unique_content_properties,nifti1
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 691, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/datalad_neuroimaging/tests/test_bids2scidata.py", line 172, in test_real_ds
    ['a_mri_bold.txt', 'a_mri_t1w.txt', 'i_Investigation.txt', 's_study.txt'])
AssertionError: ['a_mri_t1w.txt', 'i_Investigation.txt', 's_study.txt'] != ['a_mri_bold.txt', 'a_mri_t1w.txt', 'i_Investigation.txt', 's_study.txt']
```

**Comment by yarikoptic** [comment]
nope, not flaky -- started to appear consistently on Apr 16.  Our last change is on Feb 26  so must be something in dependencies

**Comment by yarikoptic** [comment]
underlying issues is in dcm2niix, filed: https://github.com/rordenlab/dcm2niix/issues/395

**Comment by yarikoptic** [comment]
ok, just uploaded dcm2niix 1.0.20200427 to neurodebian. it should resolve this test failure
